MaxPlotsPerPlayer: 5 
#The maximum amount of plots one can have
DataProvider: 'mysql'
#The data provider where plot data is stored. Do not mess with this if you do not know how it works.
mysqlhost: 127.0.0.1
mysqluser: ""
mysqlpass: ""
mysqldb: ""
#REMEMBER TO FILL THIS DATA
UseEconomy: false 
#Use an economy plugin to add prices to things like claiming (Below)
PlotCacheSize: 100
PlotSize: 32

DefaultWorld:
  MaxPlotsPerPlayer: 5 
  #The maximum amount of plots that one can own
  ClaimPrice: 0 
  #How much it costs to claim a plot (Economy must be set to 'true')
  ClearPrice: 0 
  #How much it costs to clear a plot (Economy must be set to 'true')
  DisposePrice: 0 
  #How much it costs to dispose a plot (Economy must be set to 'true')
  ResetPrice: 0 
  #How much it costs to reset a plot (Economy must be set to 'true)
  PlotSize: 32
  #How large an island is, in chunks (16 blocks = 1 chunk)
  